In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\rohit shrivastava\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rohit shrivastava\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rohit shrivastava\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rohit shrivastava\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rohit shrivastava\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\rohit shrivastava\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [15]:
s=pd.Series([10,20,30,40,50])
print(s)
print(s.dtype)

0    10
1    20
2    30
3    40
4    50
dtype: int64
int64

In [3]:
l=[10,20,30,40]
s=pd.Series(l)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
l=[10,20,30,40]
s=pd.Series(l,index=["A","B","C","D"],name="python",dtype="float")
print(s)

A    10.0
B    20.0
C    30.0
D    40.0
Name: python, dtype: float64

In [6]:
d={"A":[10,20,30,40,50],"B":[100,200,300,400]}
s1=pd.Series(d)
print(s1)
print(type(s1))
print(s1["A"])

A    [10, 20, 30, 40, 50]
B    [100, 200, 300, 400]
dtype: object
<class 'pandas.core.series.Series'>
[10, 20, 30, 40, 50]

In [8]:
s=pd.Series(12,index=[1,2,3,4,5,6,7])
print(s)

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64

In [10]:
s1=pd.Series(12,index=[1,2,3,4,5,6,7])
s2=pd.Series(12,index=[1,2,3,4])
s3=s1+s2
print(s3)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

In [4]:
dic={"A":[10,20,30,40,50],"B":[100,200,300,400,500]}
df=pd.DataFrame(dic)
print(df)
print(type(df))
print(df["A"])

    A    B
0  10  100
1  20  200
2  30  300
3  40  400
4  50  500
<class 'pandas.core.frame.DataFrame'>
0    10
1    20
2    30
3    40
4    50
Name: A, dtype: int64

In [12]:
dic={"A":[10,20,30,40,50],"B":[100,200,300,400,500],1:[1000,2000,3000,4000,5000],
    "S":[1,2,3,4,5]}
df=pd.DataFrame(dic,columns=["A",1],index=["a","s","d","e","f"],dtype="float")
df

      A       1
a  10.0  1000.0
s  20.0  2000.0
d  30.0  3000.0
e  40.0  4000.0
f  50.0  5000.0

In [13]:
l=[[10,20,30,40,50],[100,200,300,400,500]]
df=pd.DataFrame(l)
df

     0    1    2    3    4
0   10   20   30   40   50
1  100  200  300  400  500

In [14]:
d={"A":pd.Series([1,2,3,4]),"B":pd.Series([1,2,3,4])}
df=pd.DataFrame(d)
print(df)
print()
print(df["A"][2])

   A  B
0  1  1
1  2  2
2  3  3
3  4  4

3

In [21]:
# arithmetic
df=pd.DataFrame({"A":[10,20,30,40,50],"B":[1,2,3,4,5]})
df

    A  B
0  10  1
1  20  2
2  30  3
3  40  4
4  50  5

In [17]:
df["C"]=df["A"]+df["B"]
df

    A  B   C
0  10  1  11
1  20  2  22
2  30  3  33
3  40  4  44
4  50  5  55

In [18]:
df["C"]=df["A"]-df["B"]
df

    A  B   C
0  10  1   9
1  20  2  18
2  30  3  27
3  40  4  36
4  50  5  45

In [19]:
df["C"]=df["A"]*df["B"]
df

    A  B    C
0  10  1   10
1  20  2   40
2  30  3   90
3  40  4  160
4  50  5  250

In [20]:
df["C"]=df["A"]/df["B"]
df

    A  B     C
0  10  1  10.0
1  20  2  10.0
2  30  3  10.0
3  40  4  10.0
4  50  5  10.0

In [21]:
df["C"]=df["A"]%df["B"]
df

    A  B  C
0  10  1  0
1  20  2  0
2  30  3  0
3  40  4  0
4  50  5  0

In [22]:
df["C"]=df["A"]**df["B"]
df

    A  B          C
0  10  1         10
1  20  2        400
2  30  3      27000
3  40  4    2560000
4  50  5  312500000

In [23]:
df["python"]=df["A"]<=30
df["python_1"]=df["B"]>=3
df

    A  B          C  python  python_1
0  10  1         10    True     False
1  20  2        400    True     False
2  30  3      27000    True      True
3  40  4    2560000   False      True
4  50  5  312500000   False      True

In [17]:
df.insert(1,"python_2",df["A"])

In [18]:
df

    A  python_2  B
0  10        10  1
1  20        20  2
2  30        30  3
3  40        40  4
4  50        50  5

In [24]:
df.insert(2,"python_3",[10,20,30,40,50])
df

    A  B  python_3
0  10  1        10
1  20  2        20
2  30  3        30
3  40  4        40
4  50  5        50

In [23]:
py=df.pop("python_3")
py

0    10
1    20
2    30
3    40
4    50
Name: python_3, dtype: int64

In [25]:
del df["python_3"]
df

    A  B
0  10  1
1  20  2
2  30  3
3  40  4
4  50  5

In [14]:
df=pd.DataFrame({"A":[10,20,30,40,50],"B":[1,2,3,4,5]})
df

    A  B
0  10  1
1  20  2
2  30  3
3  40  4
4  50  5

In [6]:
# read csv
df=pd.read_csv(r"C:\Users\Rohit shrivastava\Downloads\previous_application.csv")
df

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,1171956,339569,Cash loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,11,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
49995,1904808,363980,Cash loans,NaN,0.0,0.0,NaN,NaN,FRIDAY,10,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
49996,2331005,231295,Cash loans,22176.405,180000.0,216418.5,NaN,180000.0,TUESDAY,12,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-670.0,-340.0,-340.0,-338.0,1.0
49997,1960897,346691,Cash loans,NaN,0.0,0.0,NaN,NaN,WEDNESDAY,16,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
49998,1979352,363244,Cash loans,24909.390,360000.0,409896.0,NaN,360000.0,FRIDAY,18,...,XNA,36.0,high,Cash X-Sell: high,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df=pd.DataFrame({"A":[10,20,30,40,50],"B":[1,2,3,4,5]})
df

    A  B
0  10  1
1  20  2
2  30  3
3  40  4
4  50  5

In [5]:
# write csv
df.to_csv(r"C:\Users\Rohit shrivastava\Desktop\newfile.csv",index=False)
df

    A    B
0  10  100
1  20  200
2  30  300
3  40  400
4  50  500

In [2]:
d={"A":pd.Series([1,2,3,4]),"B":pd.Series([1,2,3,4])}
df1=pd.DataFrame(d)
df1

   A  B
0  1  1
1  2  2
2  3  3
3  4  4